const actionTypesAdminReviews = {
  INIT_REVIEWS_START: 'INIT_REVIEWS_START',
  INIT_REVIEWS_SUCCESS: 'INIT_REVIEWS_SUCCESS',
  INIT_REVIEWS_ERROR: 'INIT_REVIEWS_ERROR',
  EDIT_REVIEWS_START: 'EDIT_REVIEWS_START',
  EDIT_REVIEWS_SUCCESS: 'EDIT_REVIEWS_SUCCESS',
  EDIT_REVIEWS_ERROR: 'EDIT_REVIEWS_ERROR',
};

export default actionTypesAdminReviews;
