const actionTypesBookingForm = {
  INCLUDE_DATA_FROM_START_FORM: 'INCLUDE_DATA_FROM_START_FORM',
  ADD_DATA_FROM_PERSONAL_INF_FORM: 'ADD_DATA_FROM_PERSONAL_INF_FORM',
};

export default actionTypesBookingForm;
