const actionTypesBookings = {
  INIT_BOOKINGS_START: 'INIT_BOOKINGS_START',
  INIT_BOOKINGS_SUCCESS: 'INIT_BOOKINGS_SUCCESS',
  INIT_BOOKINGS_ERROR: 'INIT_BOOKINGS_ERROR',
  EDIT_FORM_TOGGLE_BUTTON: 'EDIT_FORM_TOGGLE_BUTTON',
  EDIT_FORM_SUBMIT_STOP: 'EDIT_FORM_SUBMIT_STOP',
  EDIT_FORM_SUBMIT_SUCCESS: 'EDIT_FORM_SUBMIT_SUCCESS',
  EDIT_FORM_SUBMIT_ERROR: 'EDIT_FORM_SUBMIT_ERROR',

};
export default actionTypesBookings;
