const actionTypesBookings = {
  INIT_BOOKINGS_START: 'INIT_BOOKINGS_START',
  INIT_BOOKINGS_SUCCESS: 'INIT_BOOKINGS_SUCCESS',
  INIT_BOOKINGS_ERROR: 'INIT_BOOKINGS_ERROR',
  EDIT_FORM_TOGGLE_BUTTON: 'EDIT_FORM_TOGGLE_BUTTON',
  EDIT_FORM_SUBMIT_STOP: 'EDIT_FORM_SUBMIT_STOP',
  EDIT_FORM_SUBMIT_SUCCESS: 'EDIT_FORM_SUBMIT_SUCCESS',
  EDIT_FORM_SUBMIT_ERROR: 'EDIT_FORM_SUBMIT_ERROR',
  CREATE_BOOKING_START: 'CREATE_BOOKING_START',
  CREATE_BOOKING_SUCCESS: 'CREATE_BOOKING_SUCCESS',
  CREATE_BOOKING_ERROR: 'CREATE_BOOKING_ERROR',
};
export default actionTypesBookings;
