const actionTypeReviewsTicker = {
  GET_REVIEWS_FROM_DB_START: 'GET_REVIEWS_FROM_DB_START',
  GET_REVIEWS_FROM_DB_SUCCESS: 'GET_REVIEWS_FROM_DB_SUCCESS',
  GET_REVIEWS_FROM_DB_ERROR: 'GET_REVIEWS_FROM_DB_ERROR',
};

export default actionTypeReviewsTicker;
