const actionTypesRooms = {
  INIT_ROOMS_START: 'INIT_ROOMS_START',
  INIT_ROOMS_SUCCESS: 'INIT_ROOMS_SUCCESS',
  INIT_ROOMS_ERROR: 'INIT_ROOMS_ERROR',
  // изменить заполненность комнат по мере бронирования жильцов
  EDIT_ROOMS_FULLNESS_START: 'EDIT_ROOMS_FULLNESS_START',
  EDIT_ROOMS_FULLNESS_SUCCESS: 'EDIT_ROOMS_FULLNESS_SUCCESS',
  EDIT_ROOMS_FULLNESS_ERROR: 'EDIT_ROOMS_FULLNESS_ERROR',
};
export default actionTypesRooms;
